### ISSUE TITLE
How to add json file in  output data_hash?

### ISSUE THREAD

**Issue by mailtodanish** [tango-crypto/cardano-wallet-js#31]
Hi , I am using below code to add data_hash but now I have to add json in data_hash. Please suggest.
```
const datums = this.S.PlutusList.new();
const datum = this.S.PlutusData.new_constr_plutus_data(
  this.S.ConstrPlutusData.new(
    this.S.Int.new_i32(1),
    this.S.PlutusList.new()
  )
);
datums.add(datum);
console.log("datums", datums);

let t = this.S.TransactionOutput.new(
  this.S.Address.from_bech32(ReceiveAddress),
  outputValue
);
t.set_data_hash(this.S.hash_plutus_data(datum));
outputs.add(t);
```

**Comment by leobel** [comment]
Hi @mailtodanish, taking a look to `PlutusData` it seems ver similar to `TransactionMetadatum`. Currently we don't have an equivalent method to `getTransactionMetadatum` in order to "convert" a json into a `PlutusData`. Anyway I think that looking into `getTransactionMetadatum` code you can replicate the same for `PlustusData`. I'll create a ticket to bring the `PlutusData` equivalent though.
